package golang

const fileTpl = `// Code generated by protoc-gen-auth. DO NOT EDIT!
// source: {{ .InputPath }}
package {{ pkg . }}

import (
	"github.com/appootb/protobuf/go/permission"
	"github.com/appootb/protobuf/go/service"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = permission.TokenLevel_NONE_TOKEN
var _ = service.UnaryServerInterceptor

{{ range .Services }}
{{ template "service" . }}
{{ end }}
`
