package golang

const fileTpl = `// Code generated by protoc-gen-ootb. DO NOT EDIT!
// source: {{ .InputPath }}

package {{ package . }}

import (
	"context"
	"net/http"

	"github.com/appootb/substratum/v2/gateway"
	"github.com/appootb/substratum/v2/proto/go/permission"
	"github.com/appootb/substratum/v2/service"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"golang.org/x/net/websocket"
	"google.golang.org/grpc"

	{{- range $path, $pkg := externalPackages . }}
		{{ $pkg }} "{{ $path }}"
	{{- end }}
)

// ensure the imports are used
var (
	_ = http.StatusOK
	_ = runtime.String
	_ = context.TODO()
	_ = gateway.WebStream{}
	_ = grpc.ServiceDesc{}
	_ = websocket.UnknownFrame
	_ = permission.Subject_NONE
	_ = service.UnaryServerInterceptor
)

{{ range .Services }}
	{{ template "service" . }}
{{ end }}
`
