package markdown

const fileTpl = `
# {{ .InputPath }} API Document

*Document generated by protoc-gen-markdown. DO NOT EDIT!*

> APIs

{{ range $svc := .Services }}
* [{{ $svc.Name.UpperCamelCase }}](#{{ anchorName $svc.Name }}) - {{ tocComment $svc.SourceCodeInfo }}
{{ range $method := $svc.Methods }}
{{ $url := (webUrl $method) }}
	* [{{ $method.Name.UpperCamelCase }}{{ if $url }} ({{ $url }}){{ end }}](#{{ anchorName $method.Name }}) - {{ tocComment $method.SourceCodeInfo }}
{{ end }}
{{ end }}

{{ range .Services }}
{{ template "service" . }}
{{ end }}

********

## *Embed Enums & Messages*

{{ range $enum := (embedEnums .) }}
{{ template "enum" $enum }}
{{ end }}

{{ range $message := (embedMessages .) }}
<h3 id="{{ anchorName $message.Name }}">{{ $message.Name.UpperCamelCase }}</h3>

{{ template "message" $message }}
{{ end }}
`
